### Get all tasks
GET http://localhost:5204/api/tasks

###

### Create a task
POST http://localhost:5204/api/tasks
Content-Type: application/json

{
  "title": "food shop",
  "status": "todo"
}

### Update Task

PUT http://localhost:5204/api/tasks/2
Content-Type: application/json

{
  "title": "This is an updated task",
  "status": "in-progress"
}

### Delete a task (change the id as needed)
DELETE http://localhost:5204/api/tasks/1
