### Get all tasks
GET http://localhost:5204/api/tasks

###

### Create a task
POST http://localhost:5204/api/tasks
Content-Type: application/json

{
  "title": "go to the gym",
  "status": "todo",
  "notes": "Buy fruits and vegetables",
  "priority": 4
}

### Update Task

PUT http://localhost:5204/api/tasks/8
Content-Type: application/json

{
  "title": "go to the gym",
  "status": "in-progress",
  "notes": "Leg Day",
  "priority": 3
}

### Delete a task (change the id as needed)
DELETE http://localhost:5204/api/tasks/1
